.pragma library

function generate(colors, opacity, mode, context) {
    const base = colors.base00 || "#000000";
    const surface = colors.base01 || base;
    const muted = colors.base04 || "#6a6a7a";
    const text = colors.base05 || "#ffffff";
    const error = colors.base08 || "#ff0000";
    const warning = colors.base09 || "#ffff00";
    const accent = colors.base0A || "#ffff00";
    const success = colors.base0B || "#00ff00";
    const cyan = colors.base0C || "#00ffff";
    const primary = colors[colors.primaryIdx] || colors.base0D;
    const secondary = colors[colors.secondaryIdx] || colors.base0E;

    let content = `# Generated by Yaks
foreground            ${text}
background            ${surface}
cursor                ${primary}
selection_background  ${surface}
selection_foreground  ${text}
url_color             ${secondary}

# Window borders
active_border_color     ${primary}
inactive_border_color   ${surface}
bell_border_color       ${error}

# Tab bar
active_tab_foreground   ${base}
active_tab_background   ${primary}
inactive_tab_foreground ${muted}
inactive_tab_background ${surface}
tab_bar_background      ${surface}

# ANSI Colors
# Black
color0  ${surface}
color8  ${muted}

# Red
color1  ${error}
color9  ${error}

# Green
color2  ${success}
color10 ${success}

# Yellow
color3  ${warning}
color11 ${warning}

# Blue
color4  ${primary}
color12 ${primary}

# Magenta
color5  ${secondary}
color13 ${secondary}

# Cyan
color6  ${cyan}
color14 ${cyan}

# White
color7  ${muted}
color15 ${text}
`;

    if (opacity !== undefined && opacity !== null && opacity !== "") {
        content += `\nbackground_opacity ${opacity}\n`;
    }

    const reloadCommand = `
        SOCKETS=""
        [ -S "/tmp/kitty" ] && SOCKETS="/tmp/kitty"
        DYNAMIC=$(find /tmp -maxdepth 1 -name "kitty-*" -type s 2>/dev/null || true)
        SOCKETS="$SOCKETS $DYNAMIC"
        if [ -n "$SOCKETS" ]; then
            for socket in $SOCKETS; do
                kitty @ --to "unix:$socket" set-colors -a ~/.cache/yaks/themes/kitty.conf >/dev/null 2>&1 || true
            done
            (pkill -USR1 kitty || true) &
        fi
    `;

    return {
        destination: "~/.cache/yaks/themes/kitty.conf",
        content: content,
        reloadCommand: reloadCommand
    };
}
