#!/usr/bin/env bash
# scripts/gtk4.sh
# This script is triggered by Quickshell's ThemeService.
# Args: $1 = theme_id, $2 = theme_path

THEME_ID="$1"
THEME_PATH="$2"
CONTEXT="$3"
OPACITY="${4:-1.0}"
MODE="${5:-dark}"
COLORS_JSON="$THEME_PATH/colors.json"

if [ ! -f "$COLORS_JSON" ]; then
    echo "Colors file not found: $COLORS_JSON"
    exit 1
fi

get_color_raw() {
    grep "\"$1\":" "$COLORS_JSON" | sed -E 's/.*:[[:space:]]*"([^"]*)".*/\1/' | head -n 1
}

get_color() {
    local key="$1"
    case "$key" in
        "background"|"base") key="base00" ;;
        "surface"|"surfaceAlt") key="base01" ;;
        "border"|"divider") key="base03" ;;
        "textDim"|"muted") key="base04" ;;
        "text") key="base05" ;;
        "error") key="base08" ;;
        "warning") key="base09" ;;
        "accent") key="base0A" ;;
        "success") key="base0B" ;;
        "info") key="base0C" ;;
        "primary") key="primaryIdx" ;;
        "secondary") key="secondaryIdx" ;;
    esac
    
    local val=$(get_color_raw "$key")
    if [[ "$val" == base* ]]; then
        get_color_raw "$val"
    else
        echo "$val"
    fi
}

hex_to_rgba() {
    local hex="$1"
    local alpha="$2"
    # Remove # if present
    hex=${hex#\#}
    # Ensure it's a 6-digit hex
    if [ ${#hex} -ne 6 ]; then
        echo "$1"
        return
    fi
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "rgba($r, $g, $b, $alpha)"
}

BG=$(get_color "background")
SURFACE=$(get_color "surface")
TEXT=$(get_color "text")
PRIMARY=$(get_color "primary")
ACCENT=$(get_color "accent")

# Fallbacks if colors are missing
[ -z "$BG" ] && BG=$(get_color "base")
[ -z "$ACCENT" ] && ACCENT="$PRIMARY"

# RGBA variants for background elements
BG_RGBA=$(hex_to_rgba "$BG" "$OPACITY")
SURFACE_RGBA=$(hex_to_rgba "$SURFACE" "$OPACITY")

# --- 1. Update GTK 4.0 (Libadwaita) ---
GTK4_DIR="$HOME/.config/gtk-4.0"
GTK4_THEME_CSS="$GTK4_DIR/quickshell.css"
GTK4_MAIN_CSS="$GTK4_DIR/gtk.css"

mkdir -p "$GTK4_DIR"

# Generate the specific quickshell theme file
cat <<EOF > "$GTK4_THEME_CSS"
/* Generated by Quickshell Theme Sync */
@define-color accent_bg_color $ACCENT;
@define-color accent_color $ACCENT;
@define-color window_bg_color $BG_RGBA;
@define-color window_fg_color $TEXT;
@define-color view_bg_color $SURFACE_RGBA;
@define-color view_fg_color $TEXT;
@define-color headerbar_bg_color $BG_RGBA;
@define-color headerbar_fg_color $TEXT;
@define-color card_bg_color $SURFACE_RGBA;
@define-color dialog_bg_color $BG_RGBA;
@define-color popover_bg_color $SURFACE_RGBA;
@define-color sidebar_bg_color $BG_RGBA;
@define-color sidebar_fg_color $TEXT;
@define-color sidebar_backdrop_color $BG_RGBA;
@define-color secondary_sidebar_bg_color $SURFACE_RGBA;
@define-color secondary_sidebar_backdrop_color $SURFACE_RGBA;
@define-color border_color $SURFACE;
@define-color separator_color $SURFACE;
@define-color outline_color $SURFACE;
@define-color window_outline_color $SURFACE;

/* Specific Sidebar variables often used in newer Libadwaita */
@define-color sidebar_shade_color rgba(0,0,0,0.07);
@define-color sidebar_backdrop_shade_color rgba(0,0,0,0.07);

/* Backdrop (Unfocused) states */
@define-color window_bg_color_backdrop $BG_RGBA;
@define-color window_fg_color_backdrop $TEXT;
@define-color sidebar_bg_color_backdrop $BG_RGBA;
@define-color sidebar_fg_color_backdrop $TEXT;
@define-color headerbar_bg_color_backdrop $BG_RGBA;
@define-color headerbar_fg_color_backdrop $TEXT;

/* --- Aggressive Overrides (Focus & Backdrop) --- */
/* This ensures consistency whether the window is focused or not */

window,
window:backdrop,
.navigation-sidebar,
.navigation-sidebar:backdrop,
.sidebar,
.sidebar:backdrop,
headerbar,
headerbar:backdrop,
adwviewstack,
adwviewstack:backdrop {
    background-color: $BG_RGBA;
    color: $TEXT;
}

/* Main View/List sections */
.view,
.view:backdrop,
list,
list:backdrop,
gridview,
gridview:backdrop {
    background-color: $SURFACE_RGBA;
    color: $TEXT;
}

/* Fix for Nautilus specifically */
.nautilus-window notebook stack {
    background-color: $SURFACE;
}
EOF


# --- Helper: Atomic Replace to bypass Nix Read-Only files ---
safe_write_import() {
    local target_css="$1"
    local import_line="$2"
    local existing_content=""

    if [ -f "$target_css" ]; then
        # Read existing content, removing any previous quickshell imports
        existing_content=$(grep -v "quickshell.css" "$target_css")
    fi

    # Create a temporary file
    local tmp_file=$(mktemp)
    
    # Write existing content (to preserve system themes/imports)
    echo "$existing_content" > "$tmp_file"
    # Ensure there's a newline if the file wasn't empty
    [ -n "$existing_content" ] && echo "" >> "$tmp_file"
    # Append our import at the end to ensure maximum specificity
    echo "$import_line" >> "$tmp_file"

    # CRITICAL NIXOS FIX: Overwrite the content instead of replacing the file
    # This preserves the inode and keeps the symlink intact if it's not a store path
    # We use temporary file to avoid partial writes.
    cat "$tmp_file" > "$target_css"
    rm -f "$tmp_file"
    chmod 644 "$target_css"
}

# --- 1. Update GTK 4.0 (Libadwaita) ---
GTK4_DIR="$HOME/.config/gtk-4.0"
GTK4_THEME_CSS="$GTK4_DIR/quickshell.css"
GTK4_MAIN_CSS="$GTK4_DIR/gtk.css"
GTK4_DARK_CSS="$GTK4_DIR/gtk-dark.css"

mkdir -p "$GTK4_DIR"

# Write the actual colors to quickshell.css (this file is overseen by us)
# We don't rm here to preserve the inode and avoid breaking file watches
cat <<EOF > "$GTK4_THEME_CSS"
/* Generated by Quickshell Theme Sync */
@define-color accent_bg_color $ACCENT;
@define-color accent_color $ACCENT;
@define-color window_bg_color $BG_RGBA;
@define-color window_fg_color $TEXT;
@define-color view_bg_color $SURFACE_RGBA;
@define-color view_fg_color $TEXT;
@define-color headerbar_bg_color $BG_RGBA;
@define-color headerbar_fg_color $TEXT;
@define-color card_bg_color $SURFACE_RGBA;
@define-color dialog_bg_color $BG_RGBA;
@define-color popover_bg_color $SURFACE_RGBA;
@define-color sidebar_bg_color $BG_RGBA;
@define-color sidebar_fg_color $TEXT;
@define-color sidebar_backdrop_color $BG_RGBA;
@define-color secondary_sidebar_bg_color $SURFACE_RGBA;
@define-color secondary_sidebar_backdrop_color $SURFACE_RGBA;
@define-color border_color $SURFACE;
@define-color separator_color $SURFACE;
@define-color outline_color $SURFACE;
@define-color window_outline_color $SURFACE;

/* Specific Sidebar variables often used in newer Libadwaita */
@define-color sidebar_shade_color rgba(0,0,0,0.07);
@define-color sidebar_backdrop_shade_color rgba(0,0,0,0.07);

/* Backdrop (Unfocused) states */
@define-color window_bg_color_backdrop $BG_RGBA;
@define-color window_fg_color_backdrop $TEXT;
@define-color sidebar_bg_color_backdrop $BG_RGBA;
@define-color sidebar_fg_color_backdrop $TEXT;
@define-color headerbar_bg_color_backdrop $BG_RGBA;
@define-color headerbar_fg_color_backdrop $TEXT;

/* --- Aggressive Overrides (Focus & Backdrop) --- */
window, window:backdrop,
.navigation-sidebar, .navigation-sidebar:backdrop,
.sidebar, .sidebar:backdrop,
headerbar, headerbar:backdrop,
adwviewstack, adwviewstack:backdrop {
    background-color: $BG_RGBA;
    color: $TEXT;
}

.view, .view:backdrop,
list, list:backdrop,
gridview, gridview:backdrop,
.nautilus-window notebook stack {
    background-color: $SURFACE_RGBA;
    color: $TEXT;
}
EOF
chmod 644 "$GTK4_THEME_CSS"

# Apply imports using our safe helper
IMPORT_LINE='@import url("quickshell.css");'
safe_write_import "$GTK4_MAIN_CSS" "$IMPORT_LINE"
safe_write_import "$GTK4_DARK_CSS" "$IMPORT_LINE"

# --- 2. Update GTK 3.0 ---
GTK3_DIR="$HOME/.config/gtk-3.0"
GTK3_THEME_CSS="$GTK3_DIR/quickshell.css"
GTK3_MAIN_CSS="$GTK3_DIR/gtk.css"

mkdir -p "$GTK3_DIR"
# Overwrite content to preserve inode
cat "$GTK4_THEME_CSS" > "$GTK3_THEME_CSS"
chmod 644 "$GTK3_THEME_CSS"
safe_write_import "$GTK3_MAIN_CSS" "$IMPORT_LINE"

# --- 3. Update gsettings ---
# MODE is $5 (captured above)
TARGET_GTK_THEME="adw-gtk3-dark"
COLOR_SCHEME="prefer-dark"

if [ "$MODE" = "light" ]; then
    TARGET_GTK_THEME="adw-gtk3"
    COLOR_SCHEME="prefer-light"
fi

# Apply the theme if it exists
if ls /usr/share/themes | grep -q "$TARGET_GTK_THEME"; then
    dconf write /org/gnome/desktop/interface/gtk-theme "'$TARGET_GTK_THEME'"
fi

dconf write /org/gnome/desktop/interface/color-scheme "'$COLOR_SCHEME'"

# --- 4. Force Reload (Contrast Trick) ---
if [ "$CONTEXT" != "startup" ]; then
    dconf write /org/gnome/desktop/a11y/interface/high-contrast true
    sleep 0.1
    dconf write /org/gnome/desktop/a11y/interface/high-contrast false
fi

echo "GTK Theme sync completed for $THEME_ID (Mode: $MODE)"

