#!/usr/bin/env bash
# scripts/nvim.sh
# Quickshell Hook: Updates Neovim theme colors and triggers live reload

THEME_PATH="$2"
COLORS_FILE="$THEME_PATH/colors.json"
GENERATED_FILE="$HOME/.cache/quickshell/themes/nvim.lua"

mkdir -p "$(dirname "$GENERATED_FILE")"

if [ ! -f "$COLORS_FILE" ]; then
    exit 1
fi

# Use native tools for JSON to Lua conversion
{
    echo '-- Generated by Quickshell - DO NOT EDIT'
    echo 'return {'
    # Extract key-value pairs using grep/sed and format into Lua
    # This captures base00-base0F, primaryIdx, and secondaryIdx
    grep "\": \"" "$COLORS_FILE" | sed -E 's/[[:space:]]*"([^"]+)":[[:space:]]*"([^"]+)",?$/  \1 = "\2",/' | grep -v "name ="
    echo '}'
} > "$GENERATED_FILE"

# Trigger live reload in all running Neovim instances via SIGUSR1
pkill -USR1 nvim || true
